final List<Map<String, dynamic>> allEvents = [

  {'title': 'Rock Concert', 'date': '10/30/2025', 'location': 'New York', 'category': ['Music', 'Nightlife'], 'description': 'Live music performances from various rock artists.', 'image': 'rock_concert.jpg'},
  {'title': 'Halloween Parade', 'date': '10/31/2025', 'location': 'Chicago', 'category': ['Family', 'Lifestyle'], 'description': 'Join the spooky fun with costumes and floats.', 'image': 'halloween_parade.jpg'},
  {'title': 'Jazz Night', 'date': '11/05/2025', 'location': 'Atlanta', 'category': ['Music', 'Art'], 'description': 'Enjoy an evening of smooth jazz with local musicians.', 'image': 'jazz_night.jpg'},
  {'title': 'Food Festival', 'date': '11/15/2025', 'location': 'Chicago', 'category': ['Food', 'Lifestyle', 'Family'], 'description': 'Taste dishes from top local and international chefs.', 'image': 'food_festival.jpg'},
  {'title': 'Tech Workshop', 'date': '12/01/2025', 'location': 'San Diego', 'category': ['Education', 'Professional'], 'description': 'Hands-on coding and app development sessions.', 'image': 'tech_workshop.jpg'},
  {'title': 'Art Exhibition', 'date': '12/10/2025', 'location': 'Boston', 'category': ['Art'], 'description': 'Explore contemporary artwork from emerging artists.', 'image': 'art_exhibition.jpg'},
  {'title': 'Marathon', 'date': '12/15/2025', 'location': 'Houston', 'category': ['Sports', 'Fitness'], 'description': 'Annual city marathon, open to runners of all levels.', 'image': 'marathon.jpg'},
  {'title': 'Comedy Show', 'date': '12/20/2025', 'location': 'Los Angeles', 'category': ['Nightlife', 'Lifestyle'], 'description': 'Stand-up comedy night with famous comedians.', 'image': 'comedy_show.jpg'},
  {'title': 'Wine Tasting', 'date': '01/05/2026', 'location': 'Portland', 'category': ['Lifestyle', 'Family', 'Food'], 'description': 'Sample wines from local vineyards and winemakers.', 'image': 'wine_tasting.jpg'},
  {'title': 'Film Screening', 'date': '01/15/2026', 'location': 'Seattle', 'category': ['Art', 'Music'], 'description': 'Watch indie films and participate in discussions with filmmakers.', 'image': 'film_screening.jpg'},
  {'title': 'Yoga Retreat', 'date': '01/20/2026', 'location': 'Miami', 'category': ['Fitness', 'Lifestyle'], 'description': 'Morning yoga sessions on the beach for all skill levels.', 'image': 'yoga_retreat.jpg'},
  {'title': 'Street Market', 'date': '01/25/2026', 'location': 'Denver', 'category': ['Lifestyle', 'Family', 'Food'], 'description': 'Browse handmade goods and local crafts from vendors.', 'image': 'street_market.jpg'},
  {'title': 'Music Festival', 'date': '02/01/2026', 'location': 'Jacksonville', 'category': ['Music', 'Nightlife'], 'description': 'Three-day outdoor festival featuring multiple genres.', 'image': 'music_festival.jpg'},
  {'title': 'Photography Workshop', 'date': '02/05/2026', 'location': 'Phoenix', 'category': ['Education', 'Art'], 'description': 'Learn photography techniques with hands-on exercises.', 'image': 'photography_workshop.jpg'},
  {'title': 'Theater Play', 'date': '02/10/2026', 'location': 'New York', 'category': ['Art', 'Lifestyle'], 'description': 'Live stage performance of a classic drama.', 'image': 'theater_play.jpg'},
  {'title': 'Dance Competition', 'date': '02/15/2026', 'location': 'Atlanta', 'category': ['Fitness', 'Music'], 'description': 'Watch talented dancers compete in various styles.', 'image': 'dance_competition.jpg'},
  {'title': 'Coding Bootcamp', 'date': '03/01/2026', 'location': 'Chicago', 'category': ['Education', 'Professional'], 'description': 'Intensive 3-day coding sessions for beginners and pros.', 'image': 'coding_bootcamp.jpg'},
  {'title': 'Craft Beer Festival', 'date': '03/05/2026', 'location': 'Los Angeles', 'category': ['Lifestyle', 'Food'], 'description': 'Sample local craft beers and learn about brewing.', 'image': 'beer_festival.jpg'},
  {'title': 'Farmers Market', 'date': '03/10/2026', 'location': 'Boston', 'category': ['Lifestyle', 'Family', 'Food'], 'description': 'Fresh produce and homemade goods from local farmers.', 'image': 'farmers_market.jpg'},
  {'title': 'Charity Run', 'date': '03/15/2026', 'location': 'Houston', 'category': ['Sports', 'Family'], 'description': '5k charity run to support local non-profits.', 'image': 'charity_run.jpg'},
  {'title': 'Open-Mic Night', 'date': '03/20/2026', 'location': 'Miami', 'category': ['Nightlife'], 'description': 'Showcase your talent or enjoy performances from the community.', 'image': 'open_mic.jpg'},
  {'title': 'Painting Class', 'date': '04/01/2026', 'location': 'Portland', 'category': ['Art', 'Education', 'Lifestyle'], 'description': 'Step-by-step painting lessons for beginners.', 'image': 'painting_class.jpg'},
  {'title': 'Indie Film Festival', 'date': '04/05/2026', 'location': 'Seattle', 'category': ['Art', 'Music'], 'description': 'Screenings of indie films from around the world.', 'image': 'indie_film_festival.jpg'},
  {'title': 'Cooking Workshop', 'date': '04/10/2026', 'location': 'Philadelphia', 'category': ['Education', 'Lifestyle', 'Food'], 'description': 'Hands-on cooking class with local chefs.', 'image': 'cooking_workshop.jpg'},
  {'title': 'Rock Climbing Event', 'date': '04/15/2026', 'location': 'Denver', 'category': ['Fitness', 'Sports'], 'description': 'Indoor climbing sessions and competitions.', 'image': 'rock_climbing.jpg'},
  {'title': 'Holiday Market', 'date': '04/20/2026', 'location': 'Jacksonville', 'category': ['Family', 'Lifestyle', 'Food'], 'description': 'Shop festive goods and gifts for the holiday season.', 'image': 'holiday_market.jpg'},
  {'title': 'Classical Music Concert', 'date': '04/25/2026', 'location': 'New York', 'category': ['Music', 'Art'], 'description': 'Orchestra performance of famous classical pieces.', 'image': 'classical_music.jpg'},
  {'title': 'Beach Volleyball Tournament', 'date': '05/01/2026', 'location': 'Miami', 'category': ['Sports', 'Family'], 'description': 'Join teams for a fun beach volleyball competition.', 'image': 'beach_volleyball.jpg'},
  {'title': 'Food Truck Festival', 'date': '05/15/2026', 'location': 'Phoenix', 'category': ['Lifestyle', 'Family', 'Food'], 'description': 'Taste dishes from dozens of local food trucks.', 'image': 'food_truck_festival.jpg'},
  {'title': '5v5 Soccer Tournament', 'date': '05/20/2026', 'location': 'San Diego', 'category': ['Sports', 'Fitness'], 'description': 'Compete in an adult 5v5 soccer tournament for prizes.', 'image': '5v5.jpg'},

];