final List<Map<String, dynamic>> allEvents = [

  {'title': 'Rock Concert', 'date': '2025-10-20', 'location': 'New York', 'category': ['Music', 'Nightlife'], 'description': 'Live music performances from various rock artists.'},
  {'title': 'Jazz Night', 'date': '2025-11-05', 'location': 'Atlanta', 'category': ['Music', 'Art'], 'description': 'Enjoy an evening of smooth jazz with local musicians.'},
  {'title': 'Food Festival', 'date': '2025-11-15', 'location': 'Chicago', 'category': ['Food', 'Lifestyle', 'Family'], 'description': 'Taste dishes from top local and international chefs.'},
  {'title': 'Tech Workshop', 'date': '2025-12-01', 'location': 'San Diego', 'category': ['Education', 'Professional'], 'description': 'Hands-on coding and app development sessions.'},
  {'title': 'Halloween Parade', 'date': '2025-12-05', 'location': 'Chicago', 'category': ['Family', 'Lifestyle'], 'description': 'Join the spooky fun with costumes and floats.'},
  {'title': 'Art Exhibition', 'date': '2025-12-10', 'location': 'Boston', 'category': ['Art'], 'description': 'Explore contemporary artwork from emerging artists.'},
  {'title': 'Marathon', 'date': '2025-12-15', 'location': 'Houston', 'category': ['Sports', 'Fitness'], 'description': 'Annual city marathon, open to runners of all levels.'},
  {'title': 'Comedy Show', 'date': '2025-12-20', 'location': 'Los Angeles', 'category': ['Nightlife', 'Lifestyle'], 'description': 'Stand-up comedy night with famous comedians.'},
  {'title': 'Wine Tasting', 'date': '2026-01-05', 'location': 'Portland', 'category': ['Lifestyle', 'Family', 'Food'], 'description': 'Sample wines from local vineyards and winemakers.'},
  {'title': 'Book Fair', 'date': '2026-01-10', 'location': 'Philadelphia', 'category': ['Education', 'Family'], 'description': 'Meet authors and explore a wide range of books.'},
  {'title': 'Film Screening', 'date': '2026-01-15', 'location': 'Seattle', 'category': ['Art', 'Music'], 'description': 'Watch indie films and participate in discussions with filmmakers.'},
  {'title': 'Yoga Retreat', 'date': '2026-01-20', 'location': 'Miami', 'category': ['Fitness', 'Lifestyle'], 'description': 'Morning yoga sessions on the beach for all skill levels.'},
  {'title': 'Street Market', 'date': '2026-01-25', 'location': 'Denver', 'category': ['Lifestyle', 'Family', 'Food'], 'description': 'Browse handmade goods and local crafts from vendors.'},
  {'title': 'Music Festival', 'date': '2026-02-01', 'location': 'Jacksonville', 'category': ['Music', 'Nightlife'], 'description': 'Three-day outdoor festival featuring multiple genres.'},
  {'title': 'Photography Workshop', 'date': '2026-02-05', 'location': 'Phoenix', 'category': ['Education', 'Art'], 'description': 'Learn photography techniques with hands-on exercises.'},
  {'title': 'Theater Play', 'date': '2026-02-10', 'location': 'New York', 'category': ['Art', 'Lifestyle'], 'description': 'Live stage performance of a classic drama.'},
  {'title': 'Dance Competition', 'date': '2026-02-15', 'location': 'Atlanta', 'category': ['Fitness', 'Music'], 'description': 'Watch talented dancers compete in various styles.'},
  {'title': 'Coding Bootcamp', 'date': '2026-03-01', 'location': 'Chicago', 'category': ['Education', 'Professional'], 'description': 'Intensive 3-day coding sessions for beginners and pros.'},
  {'title': 'Craft Beer Festival', 'date': '2026-03-05', 'location': 'Los Angeles', 'category': ['Lifestyle', 'Food'], 'description': 'Sample local craft beers and learn about brewing.'},
  {'title': 'Farmers Market', 'date': '2026-03-10', 'location': 'Boston', 'category': ['Lifestyle', 'Family', 'Food'], 'description': 'Fresh produce and homemade goods from local farmers.'},
  {'title': 'Charity Run', 'date': '2026-03-15', 'location': 'Houston', 'category': ['Sports', 'Family'], 'description': '5k charity run to support local non-profits.'},
  {'title': 'Stand-up Comedy', 'date': '2026-03-20', 'location': 'Miami', 'category': ['Nightlife'], 'description': 'Laugh the night away with top comedians.'},
  {'title': 'Painting Class', 'date': '2026-04-01', 'location': 'Portland', 'category': ['Art', 'Education', 'Lifestyle'], 'description': 'Step-by-step painting lessons for beginners.'},
  {'title': 'Indie Film Festival', 'date': '2026-04-05', 'location': 'Seattle', 'category': ['Art', 'Music'], 'description': 'Screenings of indie films from around the world.'},
  {'title': 'Cooking Workshop', 'date': '2026-04-10', 'location': 'Philadelphia', 'category': ['Education', 'Lifestyle', 'Food'], 'description': 'Hands-on cooking class with local chefs.'},
  {'title': 'Rock Climbing Event', 'date': '2026-04-15', 'location': 'Denver', 'category': ['Fitness', 'Sports'], 'description': 'Outdoor climbing sessions and competitions.'},
  {'title': 'Holiday Market', 'date': '2026-04-20', 'location': 'Jacksonville', 'category': ['Family', 'Lifestyle', 'Food'], 'description': 'Shop festive goods and gifts for the holiday season.'},
  {'title': 'Classical Music Concert', 'date': '2026-04-25', 'location': 'New York', 'category': ['Music', 'Art'], 'description': 'Orchestra performance of famous classical pieces.'},
  {'title': 'Beach Volleyball Tournament', 'date': '2026-05-01', 'location': 'Miami', 'category': ['Sports', 'Family'], 'description': 'Join teams for a fun beach volleyball competition.'},
  {'title': 'Poetry Reading', 'date': '2026-05-05', 'location': 'Los Angeles', 'category': ['Art', 'Education', 'Lifestyle'], 'description': 'Local poets read and discuss their work.'},
  {'title': 'Startup Pitch Night', 'date': '2026-05-10', 'location': 'San Diego', 'category': ['Professional', 'Education'], 'description': 'Watch startups pitch ideas to investors.'},
  {'title': 'Food Truck Festival', 'date': '2026-05-15', 'location': 'Phoenix', 'category': ['Lifestyle', 'Family', 'Food'], 'description': 'Taste dishes from dozens of local food trucks.'},
  {'title': '5v5 Soccer Tournament', 'date': '2026-05-20', 'location': 'San Diego', 'category': ['Sports', 'Fitness'], 'description': 'Compete in an adult 5v5 soccer tournament for prizes.'},

];